web:
  build: .
  ports:
    - "3000:3000"
  links:
    - mongodb
    - elasticsearch
  environment:
    NODE_ENV: development
    MONGO_HOST: mongodb
    ELASTICSEARCH_HOST: elasticsearch

mongodb:
  image: mongo:2.6
  volumes:
    - /data/mongodb

elasticsearch:
  image: elasticsearch
  volumes:
    - /data/elasticsearch
